Repository Nexters/BandalArt-KMP, pull requests merged in 2023-08, with the labels that each got.

#33 홈 화면 뷰모델 이벤트 처리 로직 변경 및, Exception Handling 추가
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/ServerHealthCheckRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/ExceptionWrapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/extension/HttpClient.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/CreateBandalartUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/DeleteBandalartCellUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/DeleteBandalartUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/UpdateBandalartCellUseCase.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/CellText.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeUiState.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/TempBandalartData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/TempBandalartData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/CompletionRatioProgressBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
Labels: feature, design, refactoring

#36 반다라트 생성, 목록 조회, 상세 조회, 삭제 API 구현 및 데이터 연동
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/BandalartRemoteDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/BandalartMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartDetailResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartListResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/extension/Exception.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/extension/HttpClient.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_vertical_line.xml
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartDetailEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartListEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/BandalartRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/GetBandalartListUseCase.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDeleteAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDropDownMenu.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/FixedSizeText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/String.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartDetailUiModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/TempBandalartData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/CompletionRatioProgressBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
  gradle/libs.versions.toml
Labels: feature, design

#37 셀 데이터 바텀시트로 받아오기, 셀 데이터 수정
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/UpdateBandalartRequest.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/UpdateBandalartCellEntity.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetButton.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartDatePicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartEmojiPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
Labels: feature, design

#38 반다라트 표 삭제 기능 구현
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDeleteAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDropDownMenu.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: feature

#39 Feature/main bottomsheet create delete
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/BandalartRemoteDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/BandalartMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartCellResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/UpdateBandalartRequest.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartCellEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/UpdateBandalartCellEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/UpdateBandalartEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/BandalartRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/UpdateBandalartMainCellUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/UpdateBandalartSubCellUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/UpdateBandalartTaskCellUseCase.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/EmojiText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartCellUiModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartMainCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartSubCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartTaskCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartDatePicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartEmojiPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
Labels: feature, design

#42 HomeScreen의 이벤트 분리 (다음은 컴포져블 분산, 로딩 위치 고민)
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/UpdateBandalartRequest.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/UpdateBandalartEntity.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartCellUiModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartMainCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartSubCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartDatePicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheet.kt
Labels: feature, refactoring

#41 게스트 로그인 기능 구현
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  app/src/main/kotlin/com/nexters/bandalart/android/ui/BandalartApp.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/GuestLoginLocalDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/GuestLoginRemoteDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataStoreProviderModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/NetworkModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/GuestLoginLocalDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/RecentBandalartKeyDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/LoginMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/GuestLoginTokenResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/GuestLoginRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/GuestLoginTokenRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/ServerHealthCheckRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/ExceptionWrapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/util/extension/Exception.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/GuestLoginTokenEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/GuestLoginTokenRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetGuestLoginTokenUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/GetRecentBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/SetRecentBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/login/CreateGuestLoginTokenUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/login/GetGuestLoginTokenUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/login/SetGuestLoginTokenUseCase.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/navigation/OnBoardingNavigation.kt
Labels: feature

#43 홈 화면 첫 진입시 초기화 로직 구현
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/NetworkModule.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: feature

#44 앱 아이콘 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: design

#45 네트워크 에러 다이얼로그 구현
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  core/designsystem/src/main/res/drawable/ic_circle_cross.xml
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/FixedSizeText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NetworkErrorAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/TextUnit.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
Labels: feature, design

#47 디테일, 버그 픽스
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  core/designsystem/src/main/res/raw/lottie_loading_animation.json
  core/designsystem/src/main/res/raw/lottie_splash.json
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartBottomSheet.kt
Labels: design, refactoring

#48 shareKey 파라미터 삭제
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/BandalartMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartDetailResponse.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartDetailEntity.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartDetailUiModel.kt
Labels: hotfix

#51 버그 및 필요 없는 코드 수정
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  app/src/main/res/values/splash.xml
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: hotfix, design

#50 진입 스켈레톤, 로딩 애니메이션, 실패 처리
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingScreen.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartListBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartSkeleton.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartSkeletonScreen.kt
  gradle/libs.versions.toml
Labels: feature, design

#52 실패처리 보완, 메인 이벤트 뷰모델에서 관리
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NetworkErrorAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/ThemeColor.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
Labels: feature, refactoring

#54 표 텍스트 개행, 목표 달성 화면 이동 로직 디테일 보완
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/CellText.kt
  feature/complete/build.gradle.kts
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteViewModel.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/navigation/CompleteNavigation.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
Labels: feature, design

#55 스켈레톤 화면 디자인 적용
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartSkeleton.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartSkeletonScreen.kt
Labels: design

#56 colorPicker 선택 영역 수정
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
Labels: design

#57 온보딩 목표달성 화면 로띠, 이미지 연동
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  core/designsystem/src/main/res/drawable/ic_onboarding.xml
  core/designsystem/src/main/res/raw/lottie_finish.json
  core/designsystem/src/main/res/raw/lottie_onboarding.json
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/navigation/HomeNavigation.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
Labels: feature, design

#59 넥나잇 테스트
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/Modifier.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartCellUiModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartMainCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/UpdateBandalartTaskCellModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartColorPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartDatePicker.kt
Labels: feature, design, refactoring

#58 목표 달성 화면에서 홈 화면으로 돌아오기 위한 조건 추가, 로직 구현
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/kotlin/com/nexters/bandalart/android/initialize/FirebaseCrashlyticsInitializer.kt
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  build.gradle.kts
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/CompletedBandalartKeyDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataStoreProviderModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/CompletedBandalartKeyDataStoreImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/GuestLoginLocalDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/BandalartMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_onboarding.xml
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartCellEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/BandalartRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/CheckCompletedBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/DeletedCompletedBandalrtKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/InsertCompletedBandalartKeyUseCase.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NetworkErrorAlertDialog.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartDetailUiModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartItem.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartListBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/CompletionRatioProgressBar.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
  gradle/libs.versions.toml
Labels: hotfix, feature

#63 proguard 적용
  app/proguard-debug.pro
  app/proguard-rules.pro
  build-logic/src/main/kotlin/internal/android.kt
Labels: feature

#62 api 중복 호출 방지
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: feature

#61 출시 전 예외처리 보완
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  app/src/main/kotlin/com/nexters/bandalart/android/initialize/FirebaseCrashlyticsInitializer.kt
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  app/src/main/kotlin/com/nexters/bandalart/android/ui/BandalartApp.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/CompletedBandalartKeyDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataStoreProviderModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/CompletedBandalartKeyDataStoreImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/BandalartRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/DeletedBandalrtKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/GetPrevBandalartListUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/bandalart/UpsertBandalartKeyUseCase.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetText.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
Labels: hotfix, feature

#65 로딩 시 뒷 화면 클릭 블록
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingScreen.kt
Labels: hotfix

#66 온보딩 전 로딩화면이 전체 화면이 되도록 수정
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
Labels: hotfix

#68 jks ignore
  .gitignore
Labels: hotfix, skip-ci

#69 library version update, 필요 없는 코드 제거
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: refactoring

#71 네트워크 에러 다이얼로그 버튼 텍스트 변경
  core/ui/src/main/res/values/strings.xml
Labels: design

#72 데이트 피커 초기화 버튼 오작동
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartDatePicker.kt
Labels: hotfix

#73 사용하지 않는 의존성 제거
  app/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/ui/build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#75 SigningConfig 설정, Debug 일때 난독화, proguard 제거
  .github/workflows/android-ci.yml
  .gitignore
  app/build.gradle.kts
  build-logic/src/main/kotlin/internal/android.kt
Labels: gradle

#77 debug 앱과 release 앱을 분리
  app/build.gradle.kts
  app/src/debug/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: feature, gradle

#80 처음에 반다라트가 1개일때 반다라트를 삭제했을 때, 새로운 반다라트가 생성되지 않고 무한 스켈레톤이 발생하는 문제 해결
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/NetworkModule.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: hotfix

#82 공유하기 API 중복 호출 방지 로직 추가
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/Modifier.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/MultipleEventsCutter.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/UiText.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteViewModel.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/navigation/CompleteNavigation.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: hotfix, feature

#85 version up to v1.0.1
  build-logic/src/main/kotlin/internal/constants.kt
Labels: skip-ci

#88 Custom Splash Screen 추가
  app/build.gradle.kts
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  app/src/main/kotlin/com/nexters/bandalart/android/ui/BandalartApp.kt
  app/src/main/res/values/splash.xml
  core/designsystem/src/main/res/drawable/ic_app.xml
  core/designsystem/src/main/res/drawable/ic_app_title.xml
  core/designsystem/src/main/res/drawable/ic_splash.xml
  core/ui/src/main/res/values/strings.xml
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartSkeletonScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/kotlin/com/nexters/bandalart/android/feature/splash/SplashScreen.kt
  feature/splash/src/main/kotlin/com/nexters/bandalart/android/feature/splash/SplashViewModel.kt
  feature/splash/src/main/kotlin/com/nexters/bandalart/android/feature/splash/navigation/SplashNavigation.kt
  settings.gradle.kts
Labels: feature, design

#89 cd setting
  .github/workflows/android-cd.yml
  Gemfile
  Gemfile.lock
  app/google-services.json
  build-logic/src/main/kotlin/internal/constants.kt
  build.gradle.kts
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/GoogleCloudPlatform.json
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/release-notes.txt
  fastlane/report.xml
Labels: feature, product

#93 ruby 세팅 수정
  .github/workflows/android-cd.yml
Labels: hotfix, skip-ci

#94 ruby 세팅 수정 (#93)
  .github/workflows/android-cd.yml
Labels: hotfix

#95 ruby 세팅 수정
  .github/workflows/android-cd.yml
Labels: hotfix, skip-ci

#98 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#99 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#100 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#101 gemfile 수정
  Gemfile.lock
Labels: hotfix

#103 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#104 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#105 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#107 ruby setting
  .github/workflows/android-cd.yml
Labels: hotfix

#109 cd setting
  build.gradle.kts
Labels: hotfix

#110 aab build task
  build.gradle.kts
Labels: hotfix

#111 aab build task
  build.gradle.kts
Labels: hotfix

#112 aab build
  build.gradle.kts
Labels: hotfix

#114 cd build setting
  build.gradle.kts
Labels: hotfix

#115 cd build setting
  build.gradle.kts
Labels: hotfix

#116 ci build setting
  build.gradle.kts
Labels: hotfix

#122 cd setting
  .github/workflows/android-cd.yml
Labels: hotfix

#123 cd build setting
  .github/workflows/android-cd.yml
  app/build.gradle.kts
Labels: hotfix

#125 cd setting build
  app/build.gradle.kts
Labels: hotfix

#127 메인 화면의 이모지 업데이트 로직 변경
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BandalartEmojiBottomSheet.kt
Labels: feature
