Repository Nexters/BandalArt-KMP, pull requests merged in 2023-07, with the labels that each got.

#1 디렉토리 구조를 활성화 하기 위해 파일 추가
  data/src/main/kotlin/com/nexters/bandalart/data/datasource/TokenDataSource.kt
  domain/src/main/kotlin/com/nexters/bandalart/domain/MyClass.kt
Labels: bug, skip-ci

#3 Ktlint failed to parse 이슈 해결
  .idea/inspectionProfiles/Project_Default.xml
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: skip-ci

#6 네트워크 환경 구축
  data/build.gradle.kts
  data/src/main/kotlin/com/nexters/bandalart/android/data/di/NetworkModule.kt
  gradle/libs.versions.toml
  secrets.properties
Labels: enhancement

#7 DI 모듈 생성 및 domain 레이어 수정
  data/src/main/kotlin/com/nexters/bandalart/android/data/datasource/GuestLoginTokenDataSource.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/di/DataSourceModule.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/di/DataStoreProviderModule.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/local/DataStoreProvider.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/local/datasource/GuestLoginTokenDataSourceImpl.kt
  data/src/main/kotlin/com/nexters/bandalart/android/data/repository/GuestLoginTokenRepositoryImpl.kt
  domain/src/main/kotlin/com/nexters/bandalart/android/domain/repository/GuestLoginTokenRepository.kt
  domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/GetGuestLoginTokenUseCase.kt
  domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/GetGuestLoginTokenUseCaseImpl.kt
  domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/SetGuestLoginTokenUseCase.kt
  domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/SetGuestLoginTokenUseCaseImpl.kt
Labels: enhancement, refactoring

#10 SplashScreen API 적용
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/nexters/bandalart/android/presentation/MainActivity.kt
  presentation/src/main/res/values/splash.xml
Labels: enhancement

#9 컴포즈 관련 라이브러리 추가
  gradle/libs.versions.toml
Labels: enhancement

#11 Project Architecture 변경 :
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/splash.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/datasource/GuestLoginTokenDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/di/DataStoreProviderModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/di/NetworkModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/local/datasource/GuestLoginTokenDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/data/repository/GuestLoginTokenRepositoryImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/ui/theme/Color.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/ui/theme/Theme.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/ui/theme/Type.kt
  core/domain/build.gradle.kts
  core/domain/src/main/kotlin/com/nexters/bandalart/android/domain/repository/GuestLoginTokenRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/GetGuestLoginTokenUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/domain/usecase/SetGuestLoginTokenUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/nexters/bandalart/android/presentation/MainActivity.kt
  settings.gradle.kts
Labels: refactoring

#13 SERVER_BASE_URL github secrets에 추가
  .github/workflows/android-ci.yml
  .gitignore
Labels: enhancement

#14 최근 반다라트 키값 DataStore 설정
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/GuestLoginTokenDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/RecentBandalartKeyDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/GuestLoginTokenDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/RecentBandalartKeyDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/GuestLoginTokenRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/RecentBandalartKeyRepositoryImpl.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/GuestLoginTokenRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/RecentBandalartKeyRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetGuestLoginTokenUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetRecentBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/SetRecentBandalartKeyUseCase.kt
Labels: enhancement

#15 gitignore 에 등록된 파일 develop 에서 제거
  .github/workflows/android-ci.yml
  secrets.properties
Labels: bug

#17 서버 헬스 체크 API 통신 구현
  app/src/main/kotlin/com/nexters/bandalart/android/MainActivity.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/NetworkModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/ServerHealthCheckRepositoryImpl.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/ServerHealthCheckRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/CheckServerHealthUseCase.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
Labels: feature

#19 반다라트 API 연동
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/BandalartRemoteDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/datasource/RecentBandalartKeyDataSource.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/DataStoreProvider.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/local/datasource/RecentBandalartKeyDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/mapper/BandalartMapper.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartCellResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartDetailResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/model/bandalart/BandalartListResponse.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/remote/datasource/BandalartRemoteDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/BandalartRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/bandalart/android/core/data/repository/RecentBandalartKeyRepositoryImpl.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Color.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Font.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartCellEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartDetailEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/entity/BandalartListEntity.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/BandalartRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/GuestLoginTokenRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/RecentBandalartKeyRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/repository/ServerHealthCheckRepository.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetBandalartDetailUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetBandalartListUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetBandalartMainCellUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/GetRecentBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/usecase/SetRecentBandalartKeyUseCase.kt
  core/domain/src/main/kotlin/com/nexters/bandalart/android/core/domain/util/SuspendCatching.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/CellText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/TextUnit.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeUiState.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/TempBandalartData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/mapper/BandalartMapper.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/BandalartMainCellUiModel.kt
  gradle/libs.versions.toml
Labels: feature

#20 홈 화면 UI 구현
  app/src/main/kotlin/com/nexters/bandalart/android/navigation/BandalartNavHost.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Color.kt
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_app.xml
  core/designsystem/src/main/res/drawable/ic_hamburger.xml
  core/designsystem/src/main/res/drawable/ic_option.xml
  core/designsystem/src/main/res/drawable/ic_share.xml
  core/designsystem/src/main/res/drawable/ic_smile.xml
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/LoadingWheel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/LinearProgressBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/navigation/HomeNavigation.kt
Labels: feature, design

#21 홈 화면 UI 디테일 추가
  core/designsystem/src/main/res/drawable/ic_add.xml
  core/designsystem/src/main/res/drawable/ic_cell_add.xml
  core/designsystem/src/main/res/drawable/ic_cell_check.xml
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/drawable/ic_edit.xml
  core/designsystem/src/main/res/drawable/ic_vertical_line.xml
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeTopBar.kt
Labels: design

#22 온보딩 화면 구현
  core/designsystem/src/main/res/raw/lottie_empty_box.json
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/CellText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingWheel.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NavButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/TitleText.kt
  feature/complete/build.gradle.kts
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/PagerIndicator.kt
Labels: design

#23 바텀 시트 UI 구현
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Color.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BottomSheetButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BottomSheetSpacer.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BottomSheetText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BottomSheetTitle.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/DatePickerUI.kt
Labels: feature, design

#24 목표 달성 화면 UI 구현
  core/designsystem/src/main/res/drawable/ic_gallery.xml
  core/designsystem/src/main/res/drawable/ic_right_arrow.xml
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/EmojiText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/StyledText.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/PagerIndicator.kt
Labels: feature, design

#28 얼럿 다이얼로그(표 삭제), 드롭 다운 메뉴 UI 구현
  core/designsystem/src/main/kotlin/com/nexters/bandalart/android/core/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_delete.xml
  core/designsystem/src/main/res/drawable/ic_image.xml
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDeleteAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDropDownMenu.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
Labels: feature, design

#26 clean up
  app/src/main/kotlin/com/nexters/bandalart/android/ui/BandalartApp.kt
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/drawable/ic_right_arrow.xml
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDropDownMenu.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/FixedSizeText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NavButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetDivider.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/WindowInsets.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
Labels: hotfix, design, refactoring

#29 바텀시트 관련 Detail 수정
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTextStyle.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
Labels: design

#30 bottomsheet fix
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/extension/WindowInsets.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/BottomSheetContent.kt
Labels: hotfix, design
