Repository Nexters/BandalArt-KMP, pull requests merged in 2024-01, with the labels that each got.

#153 Component, Screen Preview 구성
  app/src/main/kotlin/com/nexters/bandalart/android/MainViewModel.kt
  app/src/main/kotlin/com/nexters/bandalart/android/ui/BandalartApp.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/ComponentPreview.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/DevicePreview.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/WindowInsets.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/AppTitle.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDeleteAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/BandalartDropDownMenu.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/CellText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/CompletionRatioProgressBar.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/EmojiText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/FixedSizeText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/LoadingIndicator.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/NetworkErrorAlertDialog.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/PagerIndicator.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/SaveImageButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/TitleText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetButton.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetDivider.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetText.kt
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/component/bottomsheet/BottomSheetTopBar.kt
  core/ui/src/main/res/values/strings.xml
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteViewModel.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/ui/CompleteBandalart.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/ui/CompleteTopBar.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/BandalartBottomSheetViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/DummyBandalartCellData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/DummyBandalartChartData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/DummyBandalartDetailData.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/model/DummyBandalartList.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeHeader.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeShareButton.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/HomeTopBar.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartCell.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartCellGrid.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartChart.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartColorPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartDatePicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartEmojiBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartEmojiPicker.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartItem.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartListBottomSheet.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartSkeleton.kt
  feature/home/src/main/kotlin/com/nexters/bandalart/android/feature/home/ui/bandalart/BandalartSkeletonScreen.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/kotlin/com/nexters/bandalart/android/feature/splash/SplashScreen.kt
  gradle/libs.versions.toml
Labels: feature, design, refactoring

#154 CompleteScreen 가로모드, 태블릿 대응
  core/ui/src/main/kotlin/com/nexters/bandalart/android/core/ui/DevicePreview.kt
  feature/complete/src/main/kotlin/com/nexters/bandalart/android/feature/complete/CompleteScreen.kt
  feature/onboarding/src/main/kotlin/com/nexters/bandalart/android/feature/onboarding/OnBoardingScreen.kt
Labels: design

#155 v1.0.4 app update
  build-logic/src/main/kotlin/internal/constants.kt
Labels: product
